mode = "dark"
accent = "#D6FF62"
selection = "#57335F"
muted = "#AA8FB4"
background = "#211329"
dark_background = "#180D20"
darker_background = "#100916"
lighter_background = "#35203E"
foreground = "#FFF0D0"
dark_foreground = "#B29DBA"
light_foreground = "#E7CDE8"
bright_foreground = "#FFF8E9"
hyprland_active_border = "rgba(d6ff62ff) rgba(ff67beff) rgba(ff9b54ff) 45deg"
hyprland_inactive_border = "rgba(684574cc)"
red = "#FF788E"
yellow = "#FFE279"
orange = "#FF9B54"
green = "#D6FF62"
cyan = "#74E9DF"
blue = "#A9B6FF"
magenta = "#FF67BE"
brown = "#B68469"
bright_red = "#FF9BAB"
bright_yellow = "#FFEEA5"
bright_green = "#E7FF9A"
bright_cyan = "#A5FFF2"
bright_blue = "#C6CEFF"
bright_magenta = "#FFA1D6"
