background = #211329
foreground = #FFF0D0
cursor-color = #D6FF62
selection-background = #D6FF62
selection-foreground = #211329

palette = 0=#211329
palette = 1=#FF788E
palette = 2=#D6FF62
palette = 3=#FFE279
palette = 4=#A9B6FF
palette = 5=#FF67BE
palette = 6=#74E9DF
palette = 7=#FFF0D0
palette = 8=#AA8FB4
palette = 9=#FF9BAB
palette = 10=#E7FF9A
palette = 11=#FFEEA5
palette = 12=#C6CEFF
palette = 13=#FFA1D6
palette = 14=#A5FFF2
palette = 15=#FFF8E9
