foreground #FFF0D0
background #211329
selection_foreground #211329
selection_background #D6FF62

cursor #D6FF62
cursor_text_color #211329

active_border_color #D6FF62
active_tab_background #D6FF62

color0 #211329
color1 #FF788E
color2 #D6FF62
color3 #FFE279
color4 #A9B6FF
color5 #FF67BE
color6 #74E9DF
color7 #FFF0D0
color8 #AA8FB4
color9 #FF9BAB
color10 #E7FF9A
color11 #FFEEA5
color12 #C6CEFF
color13 #FFA1D6
color14 #A5FFF2
color15 #FFF8E9

active_tab_foreground #211329
inactive_tab_background #35203E
inactive_tab_foreground #E7CDE8
